// Name and group metadata for known skills.
// Used for display only — the authoritative list of skill keys
// is always derived from the [AOE Color] section of the loaded plugin.ini.

const SKILL_META = [
  { key: 'Skill0010', name: 'Storm Gust',              group: 'Wizard' },
  { key: 'Skill0011', name: 'Meteor Storm',             group: 'Wizard' },
  { key: 'Skill0012', name: 'Lord of Vermilion',        group: 'Wizard' },
  { key: 'Skill0013', name: "Heaven's Drive",           group: 'Wizard' },
  { key: 'Skill0014', name: 'Thunderstorm',             group: 'Mage' },
  { key: 'Skill0015', name: 'Grand Cross / Darkness',   group: 'Crusader' },
  { key: 'Skill007E', name: 'Safety Wall',              group: 'Mage' },
  { key: 'Skill007F', name: 'Fire Wall',                group: 'Mage' },
  { key: 'Skill0080', name: 'Warp Portal (Zone A)',     group: 'Acolyte' },
  { key: 'Skill0081', name: 'Warp Portal (Zone B)',     group: 'Acolyte' },
  { key: 'Skill0082', name: 'Warp Portal (Zone C)',     group: 'Acolyte' },
  { key: 'Skill0083', name: 'Sanctuary',                group: 'Priest' },
  { key: 'Skill0084', name: 'Magnus Exorcismus',        group: 'Priest' },
  { key: 'Skill0085', name: 'Pneuma',                   group: 'Acolyte' },
  { key: 'Skill0087', name: 'Fire Pillar',              group: 'Wizard' },
  { key: 'Skill0088', name: 'Fire Pillar (alt)',        group: 'Wizard' },
  { key: 'Skill0089', name: 'Sheltering Bliss',         group: 'Clown/Gypsy' },
  { key: 'Skill008A', name: 'Sheltering Bliss',         group: 'Clown/Gypsy' },
  { key: 'Skill008B', name: 'Sheltering Bliss',         group: 'Clown/Gypsy' },
  { key: 'Skill008C', name: 'Sheltering Bliss',         group: 'Clown/Gypsy' },
  { key: 'Skill008D', name: 'Ice Wall',                 group: 'Wizard' },
  { key: 'Skill008E', name: 'Quagmire',                 group: 'Wizard' },
  { key: 'Skill008F', name: 'Blast Mine',               group: 'Hunter' },
  { key: 'Skill0090', name: 'Skid Trap',                group: 'Hunter' },
  { key: 'Skill0091', name: 'Ankle Snare',              group: 'Hunter' },
  { key: 'Skill0092', name: 'Venom Dust',               group: 'Assassin' },
  { key: 'Skill0093', name: 'Land Mine',                group: 'Hunter' },
  { key: 'Skill0094', name: 'Shockwave Trap',           group: 'Hunter' },
  { key: 'Skill0095', name: 'Sandman',                  group: 'Hunter' },
  { key: 'Skill0096', name: 'Flasher',                  group: 'Hunter' },
  { key: 'Skill0097', name: 'Freezing Trap',            group: 'Hunter' },
  { key: 'Skill0098', name: 'Claymore Trap',            group: 'Hunter' },
  { key: 'Skill0099', name: 'Talkie Box',               group: 'Hunter' },
  { key: 'Skill009A', name: 'Volcano',                  group: 'Sage' },
  { key: 'Skill009B', name: 'Deluge',                   group: 'Sage' },
  { key: 'Skill009C', name: 'Whirlwind',                group: 'Sage' },
  { key: 'Skill009D', name: 'Land Protector',           group: 'Sage' },
  { key: 'Skill009E', name: 'Lullaby',                  group: 'Bard' },
  { key: 'Skill009F', name: 'Mental Sensing',           group: 'Bard' },
  { key: 'Skill00A0', name: 'Down Tempo',               group: 'Bard' },
  { key: 'Skill00A1', name: 'Battle Theme',             group: 'Bard' },
  { key: 'Skill00A2', name: 'Harmonic Lick',            group: 'Bard' },
  { key: 'Skill00A3', name: 'Classical Pluck',          group: 'Bard' },
  { key: 'Skill00A4', name: 'Power Cord',               group: 'Bard' },
  { key: 'Skill00A5', name: 'Acoustic Rhythm',          group: 'Bard' },
  { key: 'Skill00A6', name: 'Unchained Serenade',       group: 'Bard' },
  { key: 'Skill00A7', name: 'Perfect Tablature',        group: 'Bard' },
  { key: 'Skill00A8', name: 'Impressive Riff',          group: 'Bard' },
  { key: 'Skill00A9', name: 'Magic Strings',            group: 'Bard' },
  { key: 'Skill00AA', name: 'Song of Lutie',            group: 'Bard' },
  { key: 'Skill00AB', name: 'Hip Shaker',               group: 'Dancer' },
  { key: 'Skill00AC', name: 'Focus Ballet',             group: 'Dancer' },
  { key: 'Skill00AD', name: 'Slow Grace',               group: 'Dancer' },
  { key: 'Skill00AE', name: 'Lady Luck',                group: 'Dancer' },
  { key: 'Skill00AF', name: "Gypsy's Kiss",             group: 'Dancer' },
  { key: 'Skill00B0', name: 'Scribble',                 group: 'Rogue' },
  { key: 'Skill00B1', name: 'Bomb',                     group: 'Alchemist' },
  { key: 'Skill00B2', name: 'Romantic Rendezvous',      group: 'Other' },
  { key: 'Skill00B3', name: 'Battle Chant',             group: 'Paladin' },
  { key: 'Skill00B4', name: 'Basilica',                 group: 'High Priest' },
  { key: 'Skill00B5', name: 'Solar Heat',               group: 'Star Gladiator' },
  { key: 'Skill00B6', name: 'Blinding Mist',            group: 'Professor' },
  { key: 'Skill00B7', name: 'Fiber Lock',               group: 'Professor' },
  { key: 'Skill00B8', name: 'Gravitational Field',      group: 'High Wizard' },
  { key: 'Skill00B9', name: "Hermode's Rod",            group: 'Clown/Gypsy' },
  { key: 'Skill00BA', name: 'Desperado',                group: 'Gunslinger' },
  { key: 'Skill00BB', name: 'Watery Evasion',           group: 'Ninja' },
  { key: 'Skill00BC', name: 'Flip Tatami',              group: 'Ninja' },
  { key: 'Skill00BD', name: 'Blaze Shield',             group: 'Ninja' },
  { key: 'Skill00BE', name: 'Gunslinger Mine',          group: 'Gunslinger' },
]

// Key → { name, group } lookup for display purposes
export const SKILL_BY_KEY = Object.fromEntries(SKILL_META.map(s => [s.key, s]))

export const GROUP_COLORS = {
  Wizard:           'text-blue-400',
  Mage:             'text-blue-300',
  Priest:           'text-yellow-300',
  Acolyte:          'text-yellow-400',
  Crusader:         'text-orange-300',
  Hunter:           'text-green-400',
  Assassin:         'text-red-400',
  Sage:             'text-purple-400',
  Bard:             'text-pink-400',
  Dancer:           'text-pink-300',
  'Clown/Gypsy':    'text-rose-400',
  Rogue:            'text-gray-400',
  Alchemist:        'text-lime-400',
  Paladin:          'text-amber-300',
  'High Priest':    'text-amber-400',
  'Star Gladiator': 'text-orange-400',
  Professor:        'text-cyan-400',
  'High Wizard':    'text-indigo-400',
  Gunslinger:       'text-orange-300',
  Ninja:            'text-teal-400',
  Other:            'text-gray-500',
}
